### ISSUE TITLE
Unable to connect to neo4j v3.5.x with REST::Neo4p v0.4001

### ISSUE THREAD

**Issue by foobargeez** [majensen/rest-neo4p#31] opened 2022-01-12 01:27 UTC
Hello,
I just upgraded REST::Neo4p from v0.3030 and getting `On version pre-check: 401 Unauthorized` when connecting to neo4j v3.5.x.  Digging through the source code, noticed that module isn't passing Authorization header.

Per https://neo4j.com/docs/developer-manual/current/http-api/authentication/, `/db/data` seems to be an authenticated endpoint and need to pass Authorization header (not sure if this is applicable only to v3.x as I can query neo4j version anonymously with 4.x).

Is this an easy fix for you or do you want me to supply a patch?

Thanks!

**Comment by johannessen** [comment] 2022-01-12 15:32
Duplicate of #26 – fix is merged. For older released version, use the described workaround.

@majensen Would you please release 0.4003 to CPAN and GitHub?

**Closed as completed** 2022-01-23 03:04 UTC
Labels: duplicate
